### ISSUE TITLE
Screenshot of how the interface looks like?

### ISSUE THREAD

**Issue by AndreasEisele** [cfedermann/WMT19SrcDA#1]
Hallo Christian, dear all,

in order to drum up volunteers amongst our colleagues in translation departments, it would be helpful to show them what they will have to do. For the Ref-based evaluation, I already have own credentials and could generate such a screen shot. For the Src-based evaluation, I have entered requests for accounts in the google doc, but while still waiting for the accounts I cannot easily explain to potential volunteers how this task will look like. Can anyone help me out?

Thanks and best regards,
Andreas

**Comment by cfedermann** [comment]
Hi @AndreasEisele,

I will upload screenshots and details today. In a nutshell, we are expanding to document level by:

- Collecting direct assessments on individual segments, shown in sequence and with context; and by
- Collecting direct assessments on full documents, as a last step.

For source-based, of course, annotators will need to be bilingual, as we will not compare against a reference but instead assess the semantic transfer from source to target language.

Cheers and best, have a good day,
   Christian

**Comment by cfedermann** [comment]
Hi @AndreasEisele, I will share screenshots with you tomorrow morning, PDT. If there are more questions on the evaluation task, please send me your questions (or post a reply here). Thanks!

**Comment by cfedermann** [comment]
![appraise-src-da-ui-sentence-pair](https://user-images.githubusercontent.com/336872/58409633-52a1ee00-8025-11e9-8bf3-f550e259fd4d.png)

**Comment by cfedermann** [comment]
For *sentence pairs*, you will see a source and corresponding candidate translation. You then assess how much you agree that 

> The black text adequately expresses the meaning of the gray text in [target language]

You will see all sentences of a document in order, and then do a final assessment on document level.
For *documents*, you will see the full source document and the full candidate document, and score the same question, just on document level.
